version: "3.9"
services:
  mongo:
    image: mongo:6.0
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
    ports:
      - "27017:27017"
    volumes:
      -  ./data:/data/db
    container_name: mongo_db
    networks:
      - front
      - back

  mongo-express:
    image: mongo-express:1.0.0-alpha
    restart: always
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: example
      ME_CONFIG_BASICAUTH_USERNAME: mexpress
      ME_CONFIG_BASICAUTH_PASSWORD: mexpress
      ME_CONFIG_MONGODB_SERVER: mongo_db
    container_name: mongo_express
    ports:
      - "1808:8081"
    links:
      - mongo
    networks:
      - front

  server:
    build: .
    ports:
      - "6000:80"
    depends_on:
      - mongo
    networks:
      - back

networks:
  front:
    driver: bridge
  back:
    driver: bridge