/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

#include "oauth.h"

char **
request_authorization_1_svc(request_authorization_information *argp, struct svc_req *rqstp)
{
	static char * result;

	/*
	 * insert server code here
	 */

	return &result;
}

request_access_token_response *
request_access_token_1_svc(request_access_token_information *argp, struct svc_req *rqstp)
{
	static request_access_token_response  result;

	/*
	 * insert server code here
	 */

	return &result;
}

char **
validate_delegated_action_1_svc(validate_delegated_action_information *argp, struct svc_req *rqstp)
{
	static char * result;

	/*
	 * insert server code here
	 */

	return &result;
}

approve_request_token_information *
approve_request_token_1_svc(approve_request_token_information *argp, struct svc_req *rqstp)
{
	static approve_request_token_information  result;

	/*
	 * insert server code here
	 */

	return &result;
}
