build:
	gcc static_schedule.c -o static_schedule
	gcc dynamic_schedule.c -o dynamic_schedule
	gcc auto_schedule.c -o auto_schedule
	gcc guided_schedule.c -o guided_schedule
	gcc nowait.c -o nowait
clean:
	rm static_schedule dynamic_schedule auto_schedule nowait guided_schedule